### ISSUE TITLE
分时图不能绘画全部的数据 只显示五分钟的

### ISSUE THREAD

**Issue by WENGRUIGAN** [wordplat/ikvStockChart#10]

**Comment by wordplat** [comment]
在 XML 布局文件中添加 app:timeLineMaxCount 控制最大 entry 数量

**Comment by WENGRUIGAN** [comment]
这样啊   我都没注意这个 谢谢啊 我试试

**Comment by WENGRUIGAN** [comment]
我的依赖版本是0.1.3没有这个属性。。

**Comment by WENGRUIGAN** [comment]
原来更新了 还看到你更新了蜡烛图 空心实心  但是分时图应该是根据时间点画的

**Comment by WENGRUIGAN** [comment]
试了下 分时图可以左右小移一段 但是X轴的时间刻度仍然是五分钟等分的。

**Comment by wordplat** [comment]
我明白了你遇到的问题。你贴的那段代码，之前我写的原意是每隔一段4等分的距离，就画一根竖向网格线和一个 X 轴 Label，我代码里面的 entrySet.getEntryList().get(i).getXLabel() 写错了，xLabel 获取错了，获取成 0 到 4 的 entry label，因此出现了你说的只显示5分钟

**Comment by wordplat** [comment]
你可以给你的 entrySet 第 0 到第 4 个 entry 的 XLabel 设置上期望的时间，这看起来会有些怪，但目前能解决问题。
如果分时图不需要左右移动，让 app:timeLineMaxCount 设定的最大数量恒大于 entrySet 的最大数量。

**Comment by WENGRUIGAN** [comment]
还有K图一个问题 ，当显示没有数据的时候，点击BOLL指标会闪退 ，前三个不会，应该是空指针的问题

**Comment by WENGRUIGAN** [comment]
有什么联系方式吗，现在还是想问下你分时图按时间点画图的思路。。
