### ISSUE TITLE
I want to have such bar for working hours. How to get this? 

### ISSUE THREAD

**Issue by Rsl717** [wordplat/ikvStockChart#14]
I want to have such bar for working hours. How to get this? And whether it is possible to put a filter there ? for filtering out monthly/weekly

![](https://cloud.githubusercontent.com/assets/21261181/26141907/89d56f34-3af7-11e7-94a8-261875606e80.PNG)

**Comment by bingely** [comment]
it's amazing,foreigner develper,good

**Comment by WENGRUIGAN** [comment]
for (int i = 0 ; i < 240; i++) {
            float lineLeft = chartRect.left + i * lineWidth;
            if (i != 0 && i != 4) {
                // 绘制 三条竖向网格线
                canvas.drawLine(lineLeft, chartRect.top, lineLeft, chartRect.bottom, gridPaint);
                xLabelPaint.setTextAlign(Paint.Align.CENTER);
            } else if (i == 0) {
                xLabelPaint.setTextAlign(Paint.Align.LEFT);
            } else {
                xLabelPaint.setTextAlign(Paint.Align.RIGHT);
            }
            // 绘制 X 轴 label
            if (entrySetSize > 0) {
                canvas.drawText(
                        entrySet.getEntryList().get(i).getXLabel(),
                        lineLeft,
                        chartRect.bottom + render.getSizeColor().getXLabelSize(),
                        xLabelPaint);
                Log.d("canvas", "onComputeOver:-------------------> "+entrySet.getEntryList().get(i).getXLabel().toString());//只显示了300秒的数据
                Log.d("canvas", "onComputeOver: "+lineLeft);
            }



        }

打印了下log日志 明明是有240分钟的数据 但横坐标就是显示五分钟

**Comment by wordplat** [comment]
@Rsl717 What do you exactly mean?
![](https://ws2.sinaimg.cn/large/006tNc79gy1ffu9abjdeqj311s13odhf.jpg)

**Comment by Rsl717** [comment]
@wordplat I need the type of such a bar, I tried it myself, but as I could not before I did not use bars, if you have some options to share with me, if it's not difficult for you, I would be glad. The time of arrival or departure or lunch to come from the device through a fingerprint or face recognition, through these data I need to draw such a bar here is an example 
![photo_2017-05-22_14-50-00](https://cloud.githubusercontent.com/assets/21261181/26303130/f84e1a4a-3eff-11e7-9ab9-0ad456ed3b2c.jpg)
