### ISSUE TITLE
有个世界难题，希望作者看下

### ISSUE THREAD

**Issue by bingely** [wordplat/ikvStockChart#22]
![kcandle](https://user-images.githubusercontent.com/11975992/28257017-19a7e95c-6afa-11e7-9ba8-42d5ddf60add.gif)

**Comment by bingely** [comment]
1 我在动态刷新最后一个k蜡烛图，发现画出的蜡烛图有问题，体现在画红色蜡烛图
 2 最后一个蜡烛图浮动的横线怎么加，在你这个框架加容易吗

**Comment by lbglobal** [comment]
最后一个蜡烛图会变，我这个框架不支持实时刷新的功能

**Comment by lbglobal** [comment]
看你的需求挺特殊的，这个就需要自己画那根线了。需要把 值->坐标 的运算过程弄清楚，这样才能解决你项目中的特定需求

**Comment by bingely** [comment]
能否写个demo，画个浮动的横线。我也仿照hightlight划线原理，总是处理不好在拖动的过程中那根线会随着Y轴的变化而变化，老是停留在原处。能否指导下

**Comment by bingely** [comment]
我是这样的思路，哪里错了
`// 绘制高亮
        if (true) {
           // final float[] highlightPoint = render.getHighlightPoint();

           /* float[] highlightPoint = new float[2];
            highlightPoint[0] = 150;
            highlightPoint[1] = 150;*/
           final float horivalue = render.getHorivalue();   // 从外界传来的行情值

            highlightPoint[0] = 0;
            highlightPoint[1] = horivalue;

            // 将entry值转换为屏幕值
            render.invertMapPoints(null, highlightPoint);

            Log.i("hightlight", "之HighlightHorizolDrawing---onDrawOver: "+highlightPoint[0]+" --- "+ highlightPoint[1]);

            canvas.save();
            canvas.clipRect(contentRect);

            if (markerViewList.size() > 0) {
                for (IMarkerView markerView : markerViewList) {
                    markerView.onDrawMarkerView(canvas,
                            highlightPoint[0],
                            highlightPoint[1]);
                }
            }

            //float highlightPointY = highlightPoint[1];
           // markerView

            canvas.drawLine(contentRect.left, highlightPoint[1], contentRect.right, highlightPoint[1], highlightPaint);


            Log.i("hightlight", "之HighlightHorizolDrawing---onDrawOver: "+highlightPoint[0]+" --- "+ highlightPoint[1]);
            canvas.restore();
        }
    }`

**Comment by bingely** [comment]
```
        // 增加浮动横线
        HighlightHorizolDrawing horizolDrawing = new HighlightHorizolDrawing();
        horizolDrawing.addMarkerView(new LableYAxisTextMarkerView(stockMarkerViewHeight));
```

**Comment by bingely** [comment]
可以花时间写成这种demo不
![k](https://user-images.githubusercontent.com/11975992/28261607-7f50bd2a-6b12-11e7-85da-648f1f75a921.gif)

**Comment by lbglobal** [comment]
图中的效果可以做到，由于框架里面没有局部实时刷新的机制，所以要动起来是全部蜡烛图重绘的，在效率上会差很多

**Comment by bingely** [comment]
假设我传入的highlightPointY的值为149，却经过invertMapPoints（）方法后变成149.67,  如何保证invertMapPoints（）后还是149啊
`
           pointCache[0] = 0;
            pointCache[1] = highlightPointY;

            render.invertMapPoints(null, pointCache);
            String value = decimalFormatter.format(pointCache[1]);
`

**Comment by bingely** [comment]
> 假设我传入的highlightPointY的值为149，却经过invertMapPoints（）方法后变成149.67, 如何保证invertMapPoints（）后还是149啊


```
        pointCache[0] = 0;
        pointCache[1] = highlightPointY;

        render.invertMapPoints(null, pointCache);
        String value = decimalFormatter.format(pointCache[1]);

```

**Comment by bingely** [comment]
> 局部刷新解决了,还要在candledrawing中加入下面判断，不然会出现上影线和下影线绘制异常

```
if (entry.getClose() > entry.getHigh()) {
                entry.setHigh(entry.getClose());
            }
            if (entry.getClose() < entry.getLow()) {
                entry.setLow(entry.getClose());
            }
```

但是我划线功能还是没研究好，恳请作者出demo示例

**Comment by bingely** [comment]
划线功能，我算是也做好了
