### ISSUE TITLE
有没有交流群啊，或者作者的qq,有问题请教下

### ISSUE THREAD

**Issue by bingely** [wordplat/ikvStockChart#5]
如何将Markview显示在底部呢？？
if (contentRect.left < highlightPointX && highlightPointX < contentRect.right) {
            Entry highlightEntry = render.getEntrySet().getHighlightEntry();

            if (highlightEntry != null) {
                float width = markerTextPaint.measureText(highlightEntry.getXLabel()) + 50;

                highlightPointX = highlightPointX - width / 2;
                if (highlightPointX < contentRect.left) {
                    highlightPointX = contentRect.left;
                }
                if (highlightPointX > contentRect.right - width) {
                    highlightPointX = contentRect.right - width;
                }

                markerInsets.left= highlightPointX + inset;
                markerInsets.top = contentRect.top + inset;
                markerInsets.right = markerInsets.left + width - inset * 2;
                markerInsets.bottom = markerInsets.top + height - inset * 2;

                canvas.drawText(highlightEntry.getXLabel(),
                        markerInsets.left + markerInsets.width() / 2,
                        (markerInsets.top + markerInsets.bottom - fontMetrics.top - fontMetrics.bottom) / 2,
                        markerTextPaint);

                canvas.drawRect(markerInsets, markerBorderPaint);

                canvas.clipRect(markerInsets, Region.Op.XOR);
            }
        }
    }

**Comment by wordplat** [comment]
不支持这个功能，需要自己画

**Comment by bingely** [comment]
怎么设置在x轴底部上面呢，现在是在x轴顶部下面

**Comment by wordplat** [comment]
0.1.3 已支持 MarkerView 对齐属性，加入了两个属性：xMarkerAlign 和 yMarkerAlign
```xml
    <com.wordplat.ikvstockchart.InteractiveKLineView
        android:id="@+id/kLineView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:yLabelAlign="right"
        app:xMarkerAlign="bottom"
        app:yMarkerAlign="left"/>
```

**Comment by bingely** [comment]
厉害

**Comment by WENGRUIGAN** [comment]
同想问一些问题 想要Q联系方式
