### ISSUE TITLE
能否问问作者，画蜡烛图的思路啊

### ISSUE THREAD

**Issue by bingely** [wordplat/ikvStockChart#9]
我看到蜡烛图间距的逻辑，至于蜡烛图宽度和高度，愣是没看到里面的具体逻辑，能否稍微指导下，宽度是具体值吗？

**Comment by wordplat** [comment]
蜡烛的宽度和高度都不是具体值，由于程序在坐标计算方式上的限制，不能够自由修改蜡烛的宽度和高度

**Comment by WENGRUIGAN** [comment]
想把蜡烛图画成空心的 是在KLineRender方法里面吗

**Comment by bingely** [comment]
我在这个类中修改

**Comment by bingely** [comment]
我在CandleDrawing中修改

**Comment by WENGRUIGAN** [comment]
楼上的我们加下联系方式吧 我QQ229478140 我重写了很多 解决了

**Comment by bingely** [comment]
我吗？你不是都解决了吗

**Comment by WENGRUIGAN** [comment]
哦 那个是解决了 还要分时图的问题 想一起问问

**Comment by bingely** [comment]
我还没做过分时图

**Comment by WENGRUIGAN** [comment]
分时图只能画一部分 就五分钟 打印了源码画的代码部分 就画300个X轴坐标
